test workflow config 4

diff --git a/.github/workflows/dev-cd.yml b/.github/workflows/dev-cd.yml
--- a/.github/workflows/dev-cd.yml
+++ b/.github/workflows/dev-cd.yml
@@ -47,7 +47,14 @@ jobs:
         with:
           args: zip -qq -r circle-search.zip .env
       - name: test log # TODO: remove
-        run: echo "Secret length: ${#MY_SECRET}"
+        shell: bash
+        run: |
+          if [ -n "${MY_SECRET}" ]; then
+            echo "Secret length: ${#MY_SECRET}"
+          else
+            echo "Secret is missing or empty"
+            exit 1
+          fi
         env:
           MY_SECRET: ${{ secrets.SSH_DEVELOP_HOST }}
       - name: copy file via ssh
